services:
  bsimgbed:
    image: bsimgbed:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsimgbed
    restart: unless-stopped
    ports:
      - "8092:3000"
    volumes:
      - ./db:/app/db
      - ./uploads:/app/uploads
    environment:
      NODE_ENV: production
      HOST: "0.0.0.0"
      PORT: "3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"